### ISSUE TITLE
String::cmp()'s behavior

### ISSUE THREAD

**Issue by gyroknight** [chasebish/cwc_object_string#1]
Can we change the behavior of `String::cmp()` to match `strcmp()` where any value <0 means `this` string is less than `s`, 0 means they're the same, and >0 is `this` string is greater than `s`?

[http://www.cplusplus.com/reference/cstring/strcmp/](http://www.cplusplus.com/reference/cstring/strcmp/)

**Comment by chasebish** [comment]
Clarified this with #4
