### ISSUE TITLE
There are no useful methods in string

### ISSUE THREAD

**Issue by MHebes** [chasebish/cwc_object_string#14]
How would one actually use string? We need a way to print it or get a char array out of it or something.

**Comment by chasebish** [comment]
I think it may be worth adding a `char* get()` that returns a copy of the value. Do you have any suggestions?

**Comment by MHebes** [comment]
I’m down to call it `get`, maybe it could have this behavior https://en.cppreference.com/w/cpp/string/basic_string/c_str ?
