### ISSUE TITLE
Using references instead of raw pointers

### ISSUE THREAD

**Issue by gyroknight** [chasebish/cwc_object_string#2]
Changing the signatures of methods that use pointers like `String*` and `Object*` to references (`String&` and `Object&`) is probably a good idea; it eliminates `nullptr` checking and is safer than using raw pointers.

**Comment by MHebes** [comment]
Counter point: the equals() method should allow for a nullptr

**Comment by gyroknight** [comment]
Should you really be comparing against a `nullptr` anyways though? IMO, if you're calling `equals()` with a `nullptr`, something has probably already gone wrong earlier in the program and you shouldn't continue. If pointer comparison is really important, equality checking is already provided by `dynamic_cast<>()`.

**Comment by chasebish** [comment]
I agree with @MHebes that `nullptr` be allowed and that `equals()` should handle that case

**Comment by gyroknight** [comment]
I've done a bit of experimenting, and you can actually use `nullptr` with references:
```
class Test {
   public:
    bool equals(Test& t) {
        return this == &t;
    }
}

int main(int argc, char* argv[]) {
    Test* a = new Test();
    Test* b = nullptr;

    // Outputs 0 as expected
    std::cout << a->equals(*b) << std::endl;
}
```

So my initial point about references not allowing `nullptr`s is incorrect. However, references are still safer than pointers since they're [immutable after assignment](https://www.geeksforgeeks.org/passing-by-pointer-vs-passing-by-reference-in-c/).

Alternatively, the signatures could be changed to `String* const` and `Object* const` to make sure they aren't mutated in the function.

**Comment by gyroknight** [comment]
Apparently, references to `nullptr`s are [undefined behavior](https://stackoverflow.com/questions/4364536/is-null-reference-possible); I assume the reason it works in my example is that I only compare the addresses and never attempt to access anything from `b`.

In the end, whether we use `String&` and `Object&` versus `String* const` and `Object* const` doesn't seem to guarantee safety since trying to access a `nullptr` will cause a crash regardless. The inputs should be immutable though at the very least to reduce some of the possible errors.

**Comment by gyroknight** [comment]
The `const` qualifier should probably be added to any method using a pointer, unless there's a good reason that the user should be able to mutate the pointer value within the method.

**Comment by MHebes** [comment]
@gyroknight isn't that just an implementation detail though?

**Comment by gyroknight** [comment]
No, because the qualifier is part of the signature, and therefore enforced by the interface.

**Comment by chasebish** [comment]
I agree with @gyroknight that const should be added to all methods that take in a pointer. I've updated the API per #5
