### ISSUE TITLE
Replace definitions with stub declarations

### ISSUE THREAD

**Issue by MHebes** [chasebish/cwc_object_string#7]
As it stands these headers won't link with tests (even if those tests just fail). Suggest to add blank method stubs so these headers will compile out of the box, and just not do anything.

**Comment by MHebes** [comment]
I'll do this but only if people agree it would be useful

**Comment by chasebish** [comment]
What do you mean by "won't link with tests"?

**Comment by MHebes** [comment]
If you put these headers as-is into your public repo, and try to make your tests, you're going to get linker errors before the tests have a chance to fail, because there are no declarations.

**Comment by chasebish** [comment]
I see what you mean now. I'm not sure if it's worth updating at this point because the tests aren't meant to run until everything is fully implemented anyways. If this is a common issue though I wouldn't mind changing it.
